name: CI

on:
  push:
    branches: "**"
    pull_request:
    tags:
      - "**"

jobs:
  build-docker:
    name: Build with Docker
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image - web
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false

